=== dpa-gmbh/metadata-mapper/example/metadata-mapping-1-0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://xml.dpa.com/cl/metadatamapper/2014-08-08/" targetNamespace="http://xml.dpa.com/cl/metadatamapper/2014-08-08/" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:complexType name="ConfigType">
		<xs:sequence>
			<xs:element name="timezone" type="xs:string">
				<xs:annotation>
					<xs:documentation>Timezone to be used to convert date/time values into string representation</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="iim">
				<xs:annotation>
					<xs:documentation>IIM (record 2) specific configuration</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="charset" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>Characterset used within the IIM record</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="characterMappingRef" type="xs:IDREF" use="optional">
						<xs:annotation>
							<xs:documentation>Reference onto a character mapping table to replace e.g. diacritc characters to the target namespace (see characterMapping type)</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="defaultReplaceChar" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>Default character to use, if a character from the source is not supported within the taget namespace</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="xmp">
				<xs:complexType>
					<xs:attribute name="charset" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>Characterset used within the XMP representation</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="characterMapping" type="xs:IDREF" use="optional">
						<xs:annotation>
							<xs:documentation>Reference onto a character mapping table to replace e.g. diacritc characters to the target namespace (see characterMapping type)</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="defaultReplaceChar" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>Default character to use, if a character from the source is not supported within the taget namespace</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CardinalityType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ONE"/>
			<xs:enumeration value="MANY"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="XPathReturnType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="STRING"/>
			<xs:enumeration value="NODE"/>
			<xs:enumeration value="NODELIST"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="QualifiedXPath">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="part" type="xs:string" use="optional">
					<xs:annotation>
						<xs:documentation>Reference of the part of a structure.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="rank" type="xs:integer" use="optional">
					<xs:annotation>
						<xs:documentation>In case of alternative xpath expression to evaluate the metadata, the rank is used to define the order of processing</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="returnType" type="XPathReturnType" use="optional" default="NODE">
					<xs:annotation>
						<xs:documentation>Expected return type of the xpath expression </xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="BaseMetadataType">
		<xs:sequence>
			<xs:element name="processor" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Processor to provide the source data </xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="class" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>Java class implementing the Processor interface </xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BaseMapsTo" abstract="true">
		<xs:attribute name="field" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>NName of the data set according to the IIM specification</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="part-ref" type="xs:string">
			<xs:annotation>
				<xs:documentation>Reference to a part of a structure </xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="XMPMappingTargetType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Text"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="Date"/>
			<xs:enumeration value="LangAlt"/>
			<xs:enumeration value="Struct"/>
            <xs:enumeration value="Sequence"/>
            <xs:enumeration value="Bag"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="XMPMapsTo">
		<xs:complexContent>
			<xs:extension base="BaseMapsTo">
				<xs:sequence>
					<xs:element name="mapsTo" type="XMPMapsTo" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="targetNamespace" use="required">
					<xs:annotation>
						<xs:documentation>XMP namespace of this metadata</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"/>
							<xs:enumeration value="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"/>
							<xs:enumeration value="http://purl.org/dc/elements/1.1/"/>
							<xs:enumeration value="http://ns.adobe.com/photoshop/1.0/"/>
							<xs:enumeration value="http://ns.adobe.com/xap/1.0/rights/"/>
							<xs:enumeration value="http://ns.useplus.org/ldf/xmp/1.0/"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="targetType" type="XMPMappingTargetType" use="required">
					<xs:annotation>
						<xs:documentation>Type of the metadata regarding the XMP specification</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="XMPMapping">
		<xs:complexContent>
			<xs:extension base="BaseMetadataType">
				<xs:sequence>
					<xs:element name="mapsTo" type="XMPMapsTo" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>Defintiion of the target data object within the XMP container</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="IIMMappingTargetType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="STRING"/>
			<xs:enumeration value="LIST_OF_STRING"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="IIMMapping">
		<xs:complexContent>
			<xs:extension base="BaseMetadataType">
				<xs:sequence>
					<xs:element name="mapsTo" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>Defiinition of the target data set within the IIM record</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="BaseMapsTo">
									<xs:attribute name="dataset" type="xs:integer" use="required">
										<xs:annotation>
											<xs:documentation>Dataset within the IIM Record 2</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="targetType" type="IIMMappingTargetType" use="required">
										<xs:annotation>
											<xs:documentation>Type of the data set</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="mapping">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:element name="config" type="ConfigType" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Configuration of the mapping e.g. target character sets, timezone etc.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="metadata" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The mapping of a specific metadata according to the IPTC Photo Metadata specification</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="xpath" type="QualifiedXPath" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="default" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="part" type="xs:string" use="optional">
												<xs:annotation>
													<xs:documentation>Reference of the part of a structure.</xs:documentation>
												</xs:annotation>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="iim" type="IIMMapping" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>IIM specific mapping for this metadata</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="xmp" type="XMPMapping" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>XMP specific mapping for this metadata</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name">
							<xs:annotation>
								<xs:documentation>Name of the metadata according to the IPTC Photo Metadata Standard</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="cardinality" type="CardinalityType" use="required">
							<xs:annotation>
								<xs:documentation>Cardinality of the metadata. This attribute is only informal and has no functionality.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="characterMapping" type="CharacterMappingType" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>A specific definition of a character mapping</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>global name of the mapping configuration</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CharacterMappingType">
		<xs:sequence>
			<xs:element name="replace" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="from" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>source character to be replaced</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="to" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>Character used to replace the source character</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="comment">
						<xs:annotation>
							<xs:documentation>String representation to display the source and destination character. This attribute has no functionality</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required">
			<xs:annotation>
				<xs:documentation>ID of a character mapping definition. This ID may referenced within the global configuration</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== dpa-gmbh/metadata-mapper/example/mapping-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping name="default" xmlns="http://xml.dpa.com/cl/metadatamapper/2014-08-08/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.dpa.com/cl/metadatamapper/2014-08-08/ file:///C:/dev/ws/service-dispatch/src/main/resources/mapping/xsd/metadata-mapping-1-0.xsd">
	<config>
		<timezone>Europe/Berlin</timezone>
		<iim charset="iso8859-15" characterMappingRef="utf8-to-iso8859-15" defaultReplaceChar="·"/>
		<xmp charset="utf-8" defaultReplaceChar="·"/>
	</config>
	<metadata name="City (legacy)" cardinality="ONE">
		<xpath rank="1"><![CDATA[//contentMeta/located/POIDetails/address/locality/name]]></xpath>
		<xpath rank="2"><![CDATA[//assert[@literal=//contentMeta/located/@literal]/POIDetails/address/locality/name]]></xpath>
		<xpath rank="3"><![CDATA[//assert[@qcode=//contentMeta/located/@qcode]/POIDetails/address/locality/name]]></xpath>
		<xpath rank="4"><![CDATA[//assert[@literal=//contentMeta/subject/@literal]/POIDetails/address/locality/name]]></xpath>
		<xpath rank="5"><![CDATA[//assert[@qcode=//contentMeta/subject/@qcode]/POIDetails/address/locality/name]]></xpath>
		<iim>
			<mapsTo dataset="90" field="City" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://ns.adobe.com/photoshop/1.0/" field="City" targetType="Text"/>
		</xmp>
	</metadata>
	<metadata name="Country (legacy)" cardinality="ONE">
		<xpath rank="1"><![CDATA[//contentMeta/located/POIDetails/address/country/name]]></xpath>
		<xpath rank="2"><![CDATA[//assert[@literal=//contentMeta/located/@literal]/POIDetails/address/country/name]]></xpath>
		<xpath rank="3"><![CDATA[//assert[@qcode=//contentMeta/located/@qcode]/POIDetails/address/country/name]]></xpath>
		<xpath rank="4"><![CDATA[//assert[@literal=//contentMeta/subject/@literal]/POIDetails/address/country/name]]></xpath>
		<xpath rank="5"><![CDATA[//assert[@qcode=//contentMeta/subject/@qcode]/POIDetails/address/country/name]]></xpath>
		<iim>
			<mapsTo dataset="101" field="Country/Primary Location Name" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://ns.adobe.com/photoshop/1.0/" field="Country" targetType="Text"/>
		</xmp>
	</metadata>
	<metadata name="Country Code (legacy)" cardinality="ONE">
		<xpath rank="1" returnType="STRING"><![CDATA[substring(//contentMeta/located/POIDetails/address/country/sameAs[substring(@qcode, 1, 12) ="iso3166-1a3:"]/@qcode,13)]]></xpath>
		<xpath rank="2" returnType="STRING"><![CDATA[substring(//contentMeta/located/POIDetails/address/country/sameAs[substring(@qcode, 1, 12) ="iso3166-1a2:"]/@qcode,13)]]></xpath>
		<xpath rank="3" returnType="STRING"><![CDATA[substring(//assert[@literal=//contentMeta/located/@literal]/POIDetails/address/country/sameAs[substring(@qcode, 1, 12) ="iso3166-1a3:"]/@qcode,13)]]></xpath>
		<xpath rank="4" returnType="STRING"><![CDATA[substring(//assert[@qcode=//contentMeta/located/@qcode]/POIDetails/address/country/sameAs[substring(@qcode, 1, 12) ="iso3166-1a3:"]/@qcode,13)]]></xpath>
		<xpath rank="5" returnType="STRING"><![CDATA[substring(//assert[@literal=//contentMeta/located/@literal]/POIDetails/address/country/sameAs[substring(@qcode, 1, 12) ="iso3166-1a2:"]/@qcode,13)]]></xpath>
		<xpath rank="6" returnType="STRING"><![CDATA[substring(//assert[@qcode=//contentMeta/located/@qcode]/POIDetails/address/country/sameAs[substring(@qcode, 1, 12) ="iso3166-1a2:"]/@qcode,13)]]></xpath>
		<iim>
			<mapsTo dataset="100" field="Country/Primary Location Code" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" field="CountryCode" targetType="Text"/>
		</xmp>
	</metadata>
	<metadata name="Headline" cardinality="ONE">
		<xpath><![CDATA[//contentMeta/headline[@rank='1' or not(@rank)]]]></xpath>
		<iim>
			<mapsTo dataset="105" field="Headline" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetType="Text" targetNamespace="http://ns.adobe.com/photoshop/1.0/" field="Headline"/>
		</xmp>
	</metadata>
	<metadata name="Description" cardinality="ONE">
		<xpath rank="1"><![CDATA[//contentMeta/description[@role='drol:caption']]]></xpath>
		<xpath rank="2"><![CDATA[//contentMeta/description[not(@role)]]></xpath>
		<iim>
			<mapsTo dataset="120" field="Caption/Abstract" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetType="LangAlt" targetNamespace="http://purl.org/dc/elements/1.1/" field="description"/>
		</xmp>
	</metadata>
	<metadata name="Intellectual Genre" cardinality="ONE">
		<xpath rank="1"><![CDATA[/newsItem/contentMeta/genre/name]]></xpath>
		<xpath rank="2"><![CDATA[/newsItem/contentMeta/genre/@literal]]></xpath>
		<iim>
			<mapsTo dataset="4" field="Object Attribute Reference" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetType="Text" targetNamespace="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" field="IntellectualGenre"/>
		</xmp>
	</metadata>
	<metadata name="Keywords" cardinality="MANY">
		<xpath><![CDATA[//contentMeta/keyword | //contentMeta/subject[not(@type = 'dpatype:category')]/name]]></xpath>
		<iim>
			<mapsTo dataset="25" field="Keywords" targetType="LIST_OF_STRING"/>
		</iim>
		<xmp>
			<mapsTo field="Subject" targetType="Bag" targetNamespace="http://purl.org/dc/elements/1.1/">
				<mapsTo field="Subject" targetNamespace="http://purl.org/dc/elements/1.1/" targetType="Text"/>
			</mapsTo>
		</xmp>
	</metadata>
	<metadata name="Province or State (legacy)" cardinality="MANY">
		<xpath rank="1"><![CDATA[//contentMeta/located/POIDetails/address/area/name]]></xpath>
		<xpath rank="2"><![CDATA[//assert[@literal=//contentMeta/located/@literal]/POIDetails/address/area/name]]></xpath>
		<xpath rank="3"><![CDATA[//assert[@qcode=//contentMeta/located/@qcode]/POIDetails/address/area/name]]></xpath>
		<xpath rank="4"><![CDATA[//assert[@literal=//contentMeta/subject/@literal]/POIDetails/address/area/name]]></xpath>
		<xpath rank="5"><![CDATA[//assert[@qcode=//contentMeta/subject/@qcode]/POIDetails/address/area/name]]></xpath>
		<iim>
			<mapsTo dataset="95" field="Province/State" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://ns.adobe.com/photoshop/1.0/" field="State" targetType="Text"/>
		</xmp>
	</metadata>
	<metadata name="Scene Code" cardinality="MANY">
		<xpath rank="1"><![CDATA[//contentMeta/genre/@qcode]]></xpath>
		<xmp>
			<mapsTo targetNamespace="http://purl.org/dc/elements/1.1/" field="Scene" targetType="Bag">
				<mapsTo field="Scene" targetNamespace="http://purl.org/dc/elements/1.1/" targetType="Text"/>
			</mapsTo>
		</xmp>
	</metadata>
	<metadata name="Subject Code" cardinality="MANY">
		<xpath rank="1" returnType="STRING"><![CDATA[substring(//contentMeta//subject[starts-with(@qcode, 'subj:')]/@qcode, 6)]]></xpath>
		<iim>
			<mapsTo field="Subject Reference" dataset="12" targetType="LIST_OF_STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" field="SubjectCode" targetType="Bag">
				<mapsTo field="SubjectCode" targetNamespace="http://purl.org/dc/elements/1.1/" targetType="Text"/>
			</mapsTo>
		</xmp>
	</metadata>
	<metadata name="Subjectlocation (legacy)" cardinality="MANY">
		<default/>
		<iim>
			<mapsTo field="Sublocation" dataset="92" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" field="Location" targetType="Text"/>
		</xmp>
	</metadata>
	<metadata name="Date Created" cardinality="ONE">
		<xpath><![CDATA[//contentMeta/contentCreated]]></xpath>
		<iim>
			<mapsTo dataset="55" field="Date Created" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://ns.adobe.com/photoshop/1.0/" targetType="Date" field="DateCreated"/>
		</xmp>
	</metadata>
	<metadata name="Description Writer" cardinality="ONE">
		<xpath rank="1"><![CDATA[//contentMeta/contributor[@role="ctrol:descrWriter"]/name]]></xpath>
		<xpath rank="2"><![CDATA[//contentMeta/contributor/name]]></xpath>
		<iim>
			<mapsTo dataset="122" field="Writer/Editor" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://ns.adobe.com/photoshop/1.0/" targetType="Text" field="CaptionWriter"/>
		</xmp>
	</metadata>
	<metadata name="Instructions" cardinality="ONE">
		<xpath><![CDATA[//itemMeta/edNote]]></xpath>
		<iim>
			<mapsTo dataset="40" field="Special Instructions" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetType="Text" targetNamespace="http://ns.adobe.com/photoshop/1.0/" field="Instructions"/>
		</xmp>
	</metadata>
	<metadata name="Job Id" cardinality="ONE">
		<xpath><![CDATA[//contentMeta/altId[@type='dpatype:orgTransRef']]]></xpath>
		<iim>
			<mapsTo dataset="103" field="Original Transmission, Reference" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetType="Text" targetNamespace="http://ns.adobe.com/photoshop/1.0/" field="TransmissionReference"/>
		</xmp>
	</metadata>
	<metadata name="Title" cardinality="ONE">
		<xpath rank="1"><![CDATA[//contentMeta/title]]></xpath>
		<xpath rank="2"><![CDATA[//contentMeta/headline[not(@rank) or @rank='1']]]></xpath>
		<xmp>
			<mapsTo targetType="LangAlt" targetNamespace="http://purl.org/dc/elements/1.1/" field="title"/>
		</xmp>
	</metadata>
	<metadata name="Copyright Notice" cardinality="ONE">
		<xpath rank="1"><![CDATA[//rightsInfo/copyrightNotice]]></xpath>
		<xpath rank="2" returnType="STRING"><![CDATA[concat('(c) ',//rightsInfo/copyrightHolder/name)]]></xpath>
		<default>(c) dpa</default>
		<iim>
			<mapsTo dataset="116" field="Copyright Notice" targetType="STRING"/>
		</iim>
		<xmp>
			<mapsTo targetType="LangAlt" targetNamespace="http://purl.org/dc/elements/1.1/" field="rights"/>
		</xmp>
	</metadata>
	<metadata name="Creator" cardinality="MANY">
		<xpath><![CDATA[//contentMeta/creator/name]]></xpath>
		<iim>
			<mapsTo dataset="80" field="By-line" targetType="LIST_OF_STRING"/>
		</iim>
		<xmp>
			<mapsTo targetNamespace="http://purl.org/dc/elements/1.1/" targetType="Sequence" field="creator"/>
		</xmp>
	</metadata>
